splash = false

# matt (desktop): 3 monitors — DP-4 (left, rotated), DP-5 (center), DP-6 (right, rotated)
wallpaper {
    monitor = DP-4
    path = /home/bubba/.config/hypr/wallpapers/teal.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-5
    path = /home/bubba/.config/hypr/wallpapers/teal.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-6
    path = /home/bubba/.config/hypr/wallpapers/teal.jpg
    fit_mode = cover
}
