shell /usr/bin/zsh
font_family      Inconsolata Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0
window_padding_width 4

# background_opacity 1.0
background_opacity 0.7

# --- Colors ---

# The basic colors
# foreground              #ffffff
background              #000000
selection_foreground    #000000
selection_background    #d8985f

# Cursor colors
cursor                  #ef596f
cursor_text_color       #000000

# URL underline color when hovering with mouse
url_color               #d8985f

# Kitty window border colors
active_border_color     #ef596f
inactive_border_color   #1a1a1a

# Tab bar colors
active_tab_foreground   #000000
active_tab_background   #ef596f
inactive_tab_foreground #ffffff
inactive_tab_background #1a1a1a

# The 16 terminal colors

# Black
color0 #000000
color8 #4d4d4d

# Red (kept standard for errors)
color1 #ff5555
color9 #ff6e6e

# Green (muted - less aggressive)
color2  #50fa7b
color10 #50fa7b

# Yellow
color3  #f1fa8c
color11 #f1fa8c

# Blue (Your Cyan)
color4  #ef596f
color12 #ef596f

# Magenta
color5  #bd93f9
color13 #ff79c6

# Cyan
color6  #ef596f
color14 #ef596f

# White
color7  #bfbfbf
color15 #ffffff
